### ISSUE TITLE
Review for BJJ

### ISSUE THREAD

**Issue by eribul** [eribul/thamortpred#47]
# How to

https://mc04.manuscriptcentral.com/bjj?URL_MASK=6aa0fec2bc1e419e81fc21dd0df31d52
Reply in dedicated boxes in system.

# Deadline
26-Sep-2020.

# To do

- [x] #49 You will find a resubmission checklist attached to this email, so please ENSURE that you address everything on the checklist in your resubmission.
- [x] Please ensure you use the space provided to respond to the reviewers' comments. If you do not do this, then there may be a significant delay.
- [x] Your manuscript should indicate where any changes have been made, using the underline feature.
- [x] Please ensure that your paper is in the citation-sequence method of referencing. That is, the references in the text are numbered in the order of their appearance and the reference list is in that order.
- [x] Please detail the role each author has had in the preparation of the paper and the study on the title page.
- [x] Please ensure figures are supplied to us in an editable format, as high quality as possible, and that all guidelines are followed as closely as possible (see resubmission checklist attached).
- [x] ETHICAL APPROVAL AND INFORMED CONSENT: When necessary please can you make sure you mention ethical approval and informed consent in the Methods section.   If not applicable or not required you need to also indicate this.
- [x] If your resubmission is not received within 2 months from the date of this email, the file will be closed.

# Editor-in-Chief Comments to Author

Reference:
- [x] #48 Bone Joint J. 2020 May;102-B(5):580-585. Modifiable risk factors for mortality in revision total hip arthroplasty for periprosthetic fracture. Victoria N Gibbs, Robert A McCulloch, Paula Dhiman, Andrew McGill, Adrian H Taylor, Antony J R Palmer, Ben J L Kendrick
- [x] #48 Bone Joint J. 2020 Jul;102-B(7_Supple_B):11-19. 2020 Frank Stinchfield Award: Identifying who will fail following irrigation and debridement for prosthetic joint infection. Noam Shohat, Karan Goswami, Timothy L Tan, Michael Yayac, Alex Soriano, Ricardo Sousa, Marjan Wouthuyzen-Bakker, Javad Parvizi, ESCMID Study Group of Implant Associated Infections (ESGIAI) and the Northern Infection Network of Joint Arthroplasty (NINJA)

# Reviewer: 1

- [x] #50 Mortality following primary THA is a rare outcome, would be more important to demonstrate predictive strength for pertinent THA related complications such as readmission, reoperation, dislocation, wound complications, length of stay, discharge to home, patient-reported outcomes.
- [x] #50 As noted above, focus limited to rare outcome. Most shared decision making revolves around a review of the most likely expected benefits and risks. While patients should be aware of their particular mortality risk, as this is a catastrophic outcome following primary THA, shared decision tools would be more helpful to focus on the more likely outcomes and complications to make an informed decision without directing undue attention to this unlikely event.
- [x] #51 Please provide age range and tabulation among patients that died within 90 days. May be inappropriate to extrapolate data from 35-year-olds if nearly all cases of mortality occur in 60+ group.
- [x] #52 Statistical method beyond the scope of most readers, a diagram explaining the process may make the description of methods more accessible.
- [x] Page 9 Line 165 "Figure 6 and ??" - Was there another figure being referenced?
- [x] #53 Can you delineate the specific inclusions for diseases of the CNS. And cutoff for diagnosis of obesity? (BMI > 30?) If you have BMI data it seems unwise to rely on the diagnosis of obesity, rather than including the specific patient level data either as a dichotomous variable or as a linear BMI variable
- [x] #54 #56 Addressed in discussion: extrapolation to countries or practices where cemented THA is less common, especially in younger patients. In the United States, for example, cemented THA is typically reserved for elderly and osteoporotic patients and this would impact the generalizability of your findings.
- [x] Page 10, line 192 "patters" I believe is typo
- [x] page 11, line 218 "cphorts" should be cohorts
- [x] page 11, line 226 "BMIt" should be BMI

# Reviewer: 2

- [x] #55 I would like to know the level of missing BMI data especially in the NJR as historically, BMI data has been poorly completed and up to 50% of BMI data can be missing. If so, has imputation modelling been used to mitigate against such missing data in the statistical modelling.
- [x] #56 #54 Why did the authors only look at cemented THA’s? And is this for cemented stems and acetabular components or were hybrid THRs also reviewed. Please clarify. In the latest NJR 2019, cemented THRs only accounted for 32% of all THRs compared to 37% for uncemented and 21% for hybrids. This means this study is representative of only 1/3 patients. Will the authors undertake further work looking at uncemented and hybrid THRs also?
- [x] #57 I would like to know if the risk of dying in 90 days was comparable to the risk if the patient had not had a THR? Ie, is there an additional risk in having a THR or is the risk the same? For example, in a 99 year old, their risk of dying may also be almost 9% just by the fact they are 99 years old. Can the authors provide comparisons to normal mortality rates? The authors have already stated (line 232) that THA was not regarded as an intervention.
- [x] #58 Data accuracy and completeness in the NJR has been an issue historically. Can the authors provide some data on data completeness and the level of missing data in the statistical analysis.
